### ISSUE TITLE
Android MissingPluginException

### ISSUE THREAD

**Issue by wheel1992** [fluttercommunity/get_version#3]
```
MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/package_info)
E/flutter (31899): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter (31899): MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/package_info)
E/flutter (31899): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:278:7)
E/flutter (31899): <asynchronous suspension>
E/flutter (31899): #1      PackageInfo.fromPlatform (package:package_info/package_info.dart:35:17)
E/flutter (31899): <asynchronous suspension>
E/flutter (31899): #2      GetVersion.projectCode (package:get_version/get_version.dart:22:49)
E/flutter (31899): <asynchronous suspension>
E/flutter (31899): #3      AdministratorMiddleware.call (package:swz_android_vms/redux/middleware/admin_middleware.dart:52:41)
E/flutter (31899): <asynchronous suspension>
E/flutter (31899): #4      Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:238:43)
E/flutter (31899): #5      RegisterMiddleware.call (package:swz_android_vms/redux/middleware/register_middleware.dart:72:9)
E/flutter (31899): <asynchronous suspension>
E/flutter (31899): #6      Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:238:43)
E/flutter (31899): #7      Store.dispatch (package:redux/src/store.dart:250:20)
E/flutter (31899): #8      _SettingScreenState._handleBuildOnceCompleted (package:swz_android_vms/screen/setting_screen.dart:333:12)
E/flutter (31899): <asynchronous suspension>
E/flutter (31899): #9      _SettingScreenState.build.<anonymous closure> (package:swz_android_vms/screen/setting_screen.dart:75:9)
E/flutter (31899): #10     _StoreStreamListenerState._init.<anonymous closure> (package:flutter_redux/flutter_redux.dart)
E/flutter (31899): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
E/flutter (31899): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:938:9)
E/flutter (31899): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
E/flutter (31899): #14     _invoke (dart:ui/hooks.dart:128:13)
E/flutter (31899): #15     _drawFrame (dart:ui/hooks.dart:117:3)
```

Library Version: ^0.0.6
Flutter 0.7.3 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 3b309bda07 (10 days ago) • 2018-08-28 12:39:24 -0700
Engine • revision af42b6dc95
Tools • Dart 2.1.0-dev.1.0.flutter-ccb16f7282

**Comment by bradintheusa** [comment]
I got this working on Android with no issue.   What was the line of code that caused this?

**Comment by AppleEducate** [comment]
Are you using the Flutter versioning from the pubspec.yaml for build and version name? If so this won't work. This only works when manually specifying build and version number in iOS and Android

**Comment by SakinaBoriwala21** [comment]
@AppleEducate I am using this plugin at other places in the App and it works fine. I am facing the issue when I wrote a test case,I am getting this error:

 MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/package_info)

For detail insight in the code: 

https://stackoverflow.com/questions/55595718/how-to-fix-missingpluginexception-package-info-caused-by-get-version-plugin

**Comment by rodydavis** [comment]
@sakina1403 thank you. Not sure why this is happening, but I will check it out

**Comment by SingleCycleKing** [comment]
@rodydavis I am using the Flutter versioning from the pubspec.yaml, in this case how can I get the version?  Thanks.

**Comment by rodydavis** [comment]
This will not work on tests. You can Mock it however
